[package]
name = "dns-sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.0.1"
env_logger = "0.6.0"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.1.0"
plot = { path = "../plot", optional = true }
prettytable-rs = { version = "0.8.0", default-features = false }
serde = { version = "1.0.81", features = [ "derive" ] }
serde_json = "1.0.33"
serde-pickle = "0.4.1"
serde_with = "0.2.5"
string_cache = "0.7.3"
structopt = "0.2.13"
sequences = { path = "../sequences/" }

[features]
default = []
