[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "dns-sequence"
version = "0.1.0"

[dependencies]
csv = "1.1.3"
env_logger = "0.7.1"
failure = "0.1.8"
log = "0.4.11"
misc_utils = "2.5.2"
once_cell = "1.4.1"
prettytable-rs = {version = "0.8.0", default-features = false}
sequences = {path = "../sequences/", features = ["read_pcap"]}
serde = {version = "1.0.116", features = ["derive"]}
serde_json = "1.0.58"
serde_with = "1.5.0-alpha.2"
string_cache = "0.8.0"
structopt = "0.3.18"
