[package]
name = "dns-sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.1.2"
env_logger = "0.7.1"
failure = "0.1.6"
log = "0.4.10"
misc_utils = "2.5.1"
once_cell = "1.3.0"
prettytable-rs = { version = "0.8.0", default-features = false }
sequences = { path = "../sequences/", features = [ "read_pcap" ] }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_json = "1.0.44"
serde_with = "1.3.1"
string_cache = "0.8.0"
structopt = "0.3.7"
