[package]
name = "dns-sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
env_logger = "0.6.0"
failure = "0.1.5"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.3.0"
plot = { path = "../plot", optional = true }
prettytable-rs = { version = "0.8.0", default-features = false }
rayon = "1.0.3"
sequences = { path = "../sequences/" }
serde = { version = "1.0.87", features = [ "derive" ] }
serde_json = "1.0.38"
serde_with = "1.0.0"
serde-pickle = "0.4.1"
string_cache = "0.7.3"
structopt = "0.2.14"

[features]
default = []
