[package]
name = "dns-sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
env_logger = "0.7.0"
failure = "0.1.6"
lazy_static = "1.4.0"
log = "0.4.8"
misc_utils = "2.4.0"
prettytable-rs = { version = "0.8.0", default-features = false }
sequences = { path = "../sequences/" }
serde = { version = "1.0.101", features = [ "derive" ] }
serde_json = "1.0.41"
serde_with = "1.3.1"
string_cache = "=0.7.3"
structopt = "0.3.3"
