[package]
name = "commoncrawldownloader"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.10"
env_logger = "0.7.1"
failure = "0.1.8"
flate2 = "1.0.14"
log = "0.4.8"
misc_utils = "2.5.2"
reqwest = { version = "0.10.4", features = [ "blocking" ] }
serde = { version = "1.0.107", features = [ "derive" ] }
serde_json = "1.0.52"
structopt = "0.3.14"
url = "2.1.1"
