[package]
name = "commoncrawldownloader"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.6"
env_logger = "0.7.1"
failure = "0.1.6"
flate2 = "1.0.13"
log = "0.4.10"
misc_utils = "2.5.1"
reqwest = "0.9.24"
serde = { version = "1.0.103", features = [ "derive" ] }
serde_json = "1.0.44"
structopt = "0.3.5"
url = "2.1.0"
