[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "commoncrawldownloader"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.15"
anyhow = "1.0.40"
env_logger = "0.8.3"
flate2 = "1.0.20"
log = "0.4.14"
misc_utils = "4.0.1"
reqwest = {version = "0.11.2", features = ["blocking"]}
serde = {version = "1.0.124", features = ["derive"]}
serde_json = "1.0.64"
structopt = "0.3.21"
url = "2.2.1"
