[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "commoncrawldownloader"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.15"
anyhow = "1.0.34"
env_logger = "0.8.2"
flate2 = "1.0.19"
log = "0.4.11"
misc_utils = "4.0.0"
reqwest = {version = "0.10.9", features = ["blocking"]}
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
structopt = "0.3.21"
url = "2.2.0"
