# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - install
  - test

cache:
  paths:
  - cargo/

variables:
  RUST_BACKTRACE: "1"
  GIT_DEPTH: "3"
  CARGO_HOME: $CI_PROJECT_DIR/cargo

install:
  stage: install
  script:
  - apt-get install protobuf-c-dev

# Use cargo to test the project
test:cargo:
  stage: test
  before_script:
  - rustup update nightly
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo +nightly build --all --verbose
  - cargo +nightly test --all --verbose
