# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

cache:
  paths:
  - cargo

variables:
  RUST_BACKTRACE: "1"
  GIT_DEPTH: "3"
  CARGO_HOME: $CI_PROJECT_DIR/cargo

# Use cargo to test the project
test:cargo:
  before_script:
  - apt-get update
  - apt-get install -y protobuf-compiler
  - rustup update nightly
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo +nightly build --all --verbose
  - cargo +nightly test --all --verbose
  - for f in ./test/data/*.json; do env RUST_BACKTRACE=1 RUST_LOG=encrypted_dns=trace cargo run --bin encrypted-dns -- "$f"; done
