exclude: "results/.*"
repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
      - id: shellcheck
        name: Run shellcheck on shell files
        language: docker_image
        entry: docker.io/koalaman/shellcheck-alpine shellcheck --color=always
        types: ["shell"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        exclude_types: ["diff", "markdown", "svg"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py36-plus"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    # https://github.com/python/black#how-black-wraps-lines
    hooks:
      - id: isort
        args:
          [
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=88",
          ]
  - repo: https://github.com/python/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
