[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[workspace]
members = [
    "chrome",
    "dnstap",
    "dns-sequence",
    "framestream",
    "plot",
    "pylib",
    "sequences",
    "taskmanager",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = true

[profile.bench]
debug = false
lto = true

[dependencies]
chrome = { path = "./chrome" }
chrono = "0.4.2"
csv = "1.0.0"
dnstap = { path = "./dnstap" }
env_logger = "0.5.10"
failure = "0.1.1"
glob = "0.2.11"
lazy_static = "1.0.1"
log = "0.4.1"
min-max-heap = "1.2.0"
misc_utils = "2.1.0"
petgraph = { version = "0.4.13", features = [ "serde-1" ] }
petgraph-graphml = "1.0.0"
rayon = "1.0.1"
sequences = { path = "./sequences" }
serde = "1.0.49"
serde_derive = "1.0.49"
serde_json = "1.0.31"
serde-pickle = "0.4.1"
structopt = "0.2.8"
url = "1.7.0"

[dependencies.serde_with]
version = "0.2.0"
features = [ "chrono" ]

[build-dependencies]
protoc-rust = "2.0.5"
