# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-overrides
cargo-features = ["profile-overrides"]

[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[workspace]
members = [
    "chrome",
    "dnstap",
    "dns-sequence",
    "framestream",
    "plot",
    "pylib",
    "sequences",
    "taskmanager",
]

[profile.dev]
opt-level = 1

# This applies to all dependencies, but not this crate or any workspace member
[profile.dev.overrides."*"]
opt-level = 3

# Build scripts and their dependencies will be compiled with -Copt-level=3
# By default, build scripts use the same rules as the rest of the profile
[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = true
lto = true

[profile.bench]
debug = false
lto = true

[[bench]]
name = "parse_chrome_json"
harness = false

[dependencies]
chrome = { path = "./chrome" }
chrono = "0.4.2"
csv = "1.0.0"
dnstap = { path = "./dnstap" }
env_logger = "0.5.10"
failure = "0.1.1"
glob = "0.2.11"
lazy_static = "1.0.1"
log = "0.4.1"
min-max-heap = "1.2.0"
misc_utils = "2.1.0"
petgraph = { version = "0.4.13", features = [ "serde-1" ] }
petgraph-graphml = "1.0.0"
rayon = "1.0.1"
sequences = { path = "./sequences" }
serde = "1.0.49"
serde_derive = "1.0.49"
serde_json = "1.0.32"
serde-pickle = "0.4.1"
structopt = "0.2.11"
url = "1.7.0"

[dependencies.serde_with]
version = "0.2.0"
features = [ "chrono" ]

[build-dependencies]
protoc-rust = "2.1.1"

[dev-dependencies]
chrome = { path = "./chrome" }
criterion = "0.2.5"
failure = "0.1.2"
misc_utils = "2.1.0"
serde_json = "1.0.32"
