[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = { version = "0.4.2", features = [ "serde" ] }
env_logger = "0.5.10"
failure = "0.1.1"
log = "0.4.1"
misc_utils = "1.4.0"
petgraph = { version = "0.4.12", features = [ "serde-1" ] }
petgraph-graphml = "1.0.0"
serde = "1.0.49"
serde_derive = "1.0.49"
serde_json = "1.0.17"
serde-pickle = "0.4.1"
structopt = "0.2.8"
url = "1.7.0"
