# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-overrides
cargo-features = ["profile-overrides"]

[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[workspace]
members = [
    "chrome",
    "countermeasures",
    "dnstap",
    "dns-sequence",
    "extract-sequence",
    "framestream",
    "pylib",
    "sequences",
    "taskmanager",
    "third-party-resources",
    "xvfb",
]

[profile.dev]
opt-level = 1

# This applies to all dependencies, but not this crate or any workspace member
[profile.dev.overrides."*"]
opt-level = 3

# Build scripts and their dependencies will be compiled with -Copt-level=3
# By default, build scripts use the same rules as the rest of the profile
[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = true
lto = true

[profile.bench]
debug = false
lto = true

[[bench]]
name = "parse_chrome_json"
harness = false

[dependencies]
chrome = { path = "./chrome" }
chrono = "0.4.7"
csv = "1.1.0"
dnstap = { path = "./dnstap" }
env_logger = "0.6.2"
failure = "0.1.5"
glob = "0.3.0"
lazy_static = "1.3.0"
log = "0.4.6"
min-max-heap = "1.2.2"
misc_utils = "2.4.0"
petgraph = { version = "0.4.13", features = [ "serde-1" ] }
petgraph-graphml = "1.0.0"
rayon = "1.1.0"
sequences = { path = "./sequences" }
serde = { version = "1.0.94", features = [ "derive" ] }
serde_json = "1.0.40"
structopt = "0.2.18"
url = "1.7.2"

[dependencies.serde_with]
version = "1.3.1"
features = [ "chrono" ]

[build-dependencies]
protoc-rust = "2.6.2"

[dev-dependencies]
chrome = { path = "./chrome" }
criterion = "0.2.11"
failure = "0.1.5"
misc_utils = "2.4.0"
serde_json = "1.0.40"

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", rev = "b4fe517a16f1596f5c483256a4bd36551812d16d" }
tokio-async-await = { git = "https://github.com/tokio-rs/tokio", rev = "b4fe517a16f1596f5c483256a4bd36551812d16d" }
trust-dns-proto = { git = "https://github.com/jonasbb/trust-dns", branch = "fix-empty-option-at-end-of-edns" }
