[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = { version = "0.4.2", features = [ "serde" ] }
csv = "1.0.0"
env_logger = "0.5.10"
failure = "0.1.1"
framestream = { path = "./framestream" }
lazy_static = "1.0.1"
log = "0.4.1"
min-max-heap = "1.2.0"
misc_utils = "1.4.0"
num-traits = "0.2.4"
petgraph = { version = "0.4.12", features = [ "serde-1" ] }
petgraph-graphml = "1.0.0"
protobuf = "2.0.2"
rayon = "1.0.1"
serde = "1.0.49"
serde_derive = "1.0.49"
serde_json = "1.0.17"
serde-pickle = "0.4.1"
structopt = "0.2.8"
trust-dns = "0.14.0"
url = "1.7.0"

[dependencies.serde_with]
version = "0.2.0"
features = [ "chrono" ]

[build-dependencies]
protoc-rust = "2.0.2"
