[package]
name = "encrypted-dns"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
env_logger = "0.5.10"
failure = "0.1.1"
log = "0.4.1"
petgraph = "0.4.12"
serde_derive = "1.0.47"
serde_json = "1.0.17"
structopt = "0.2.8"
