[package]
name = "sequences"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[[bench]]
name = "take_smallest"
harness = false

[[bench]]
name = "u8_abs"
harness = false

[dependencies]
chrono = { version = "0.4.6", features = [ "serde" ] }
dnstap = { path = "../dnstap" }
failure = "0.1.5"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.3.0"
num-traits = "0.2.6"
ordered-float = { version = "1.0.1", features = [ "serde" ] }
rayon = "1.0.3"
serde = { version = "1.0.87", features = [ "derive" ] }
serde_with = "1.0.0"
string_cache = "0.7.3"

[dev-dependencies]
criterion = "0.2.10"
min-max-heap = "1.2.2"
