[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "sequences"
version = "0.1.0"

[features]
read_pcap = ["etherparse", "itertools", "pcap-parser", "rustls"]

[[bench]]
harness = false
name = "take_smallest"

[[bench]]
harness = false
name = "u8_abs"

[dependencies]
anyhow = "1.0.38"
chrono = "0.4.19"
dashmap = "4.0.1"
dnstap = {path = "../dnstap"}
etherparse = {version = "0.9.0", optional = true}
fnv = "1.0.7"
internment = {version = "0.4.1", features = ["serde"]}
itertools = {version = "0.10.0", optional = true}
log = "0.4.13"
misc_utils = "4.0.1"
num-traits = "0.2.14"
once_cell = "1.5.2"
ordered-float = {version = "2.0.1", features = ["serde"]}
pcap-parser = {version = "0.9.3", features = ["data"], optional = true}
rand = "0.8.0"
rand_xorshift = "0.3.0"
rayon = "1.5.0"
rustls = {version = "0.19.0", optional = true}
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.61"
serde_with = {version = "1.6.0", features = ["chrono"]}
string_cache = "0.8.1"

[dev-dependencies]
criterion = "0.3.3"
min-max-heap = "1.3.0"
pretty_assertions = "0.6.1"
