[package]
name = "sequences"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[features]
read_pcap = [ "etherparse", "itertools", "pcap-parser", "ron", "rustls" ]

[[bench]]
name = "take_smallest"
harness = false

[[bench]]
name = "u8_abs"
harness = false

[dependencies]
chrono = { version = "0.4.10", features = [ "serde" ] }
dashmap = "3.2.1"
dnstap = { path = "../dnstap" }
etherparse = { version = "0.9.0", optional = true }
failure = "0.1.6"
fnv = "1.0.6"
internment = "0.3.12"
itertools = { version = "0.8.2", optional = true }
log = "0.4.8"
misc_utils = "2.5.1"
num-traits = "0.2.11"
once_cell = "1.3.1"
ordered-float = { version = "1.0.2", features = [ "serde" ] }
pcap-parser = { version = "0.8.2", features = [ "data" ], optional = true }
rand = "0.7.3"
rand_xorshift = "0.2.0"
rayon = "1.3.0"
ron = { version = "0.5.1", optional = true }
rustls = { version = "0.16.0", optional = true }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_json = "1.0.45"
serde_with = "1.4.0"
string_cache = "0.8.0"

[dev-dependencies]
criterion = "0.3.0"
min-max-heap = "1.3.0"
pretty_assertions = "0.6.1"
