[package]
name = "sequences"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[[bench]]
name = "take_smallest"
harness = false

[dependencies]
chrono = { version = "0.4.6", features = [ "serde" ] }
dnstap = { path = "../dnstap" }
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.1.0"
rayon = "1.0.3"
serde = { version = "1.0.79", features = [ "derive" ] }
serde_with = "0.2.4"
string_cache = "0.7.3"

[dev-dependencies]
criterion = "0.2.5"
min-max-heap = "1.2.0"
