[package]
name = "sequences"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[features]
read_pcap = [ "colored", "hashbrown", "itertools", "pcap", "pnet", "ron", "rustls" ]

[[bench]]
name = "take_smallest"
harness = false

[[bench]]
name = "u8_abs"
harness = false

[dependencies]
chrono = { version = "0.4.7", features = [ "serde" ] }
colored = { version = "1.8.0", optional = true }
dnstap = { path = "../dnstap" }
failure = "0.1.5"
fnv = "1.0.6"
hashbrown = { version = "0.5.0", features = [ "serde" ], optional = true }
itertools = { version = "0.8.0", optional = true }
lazy_static = "1.3.0"
log = "0.4.8"
misc_utils = "2.4.0"
num-traits = "0.2.8"
ordered-float = { version = "1.0.2", features = [ "serde" ] }
pcap = { version = "0.7.0", optional = true }
pnet = { version = "0.22.0", optional = true }
rand = "0.7.0"
rand_xorshift = "0.2.0"
rayon = "1.1.0"
ron = { version = "0.5.1", optional = true }
rustls = { version = "0.15.2", optional = true }
serde = { version = "1.0.97", features = [ "derive" ] }
serde_json = "1.0.40"
serde_with = "1.3.1"
string_cache = "0.7.3"

[dev-dependencies]
criterion = "0.2.11"
min-max-heap = "1.2.2"
pretty_assertions = "0.6.1"
