[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "sequences"
version = "0.1.0"

[features]
read_pcap = ["etherparse", "itertools", "pcap-parser", "rustls"]

[[bench]]
harness = false
name = "take_smallest"

[[bench]]
harness = false
name = "u8_abs"

[dependencies]
chrono = "0.4.19"
dashmap = "3.11.10"
dnstap = {path = "../dnstap"}
etherparse = {version = "0.9.0", optional = true}
failure = "0.1.8"
fnv = "1.0.7"
internment = {version = "0.4.1", features = ["serde"]}
itertools = {version = "0.9.0", optional = true}
log = "0.4.11"
misc_utils = "2.5.2"
num-traits = "0.2.12"
once_cell = "1.4.1"
ordered-float = {version = "2.0.0", features = ["serde"]}
pcap-parser = {version = "0.9.3", features = ["data"], optional = true}
rand = "0.7.3"
rand_xorshift = "0.2.0"
rayon = "1.4.1"
rustls = { version = "0.18.1", optional = true }
serde = {version = "1.0.116", features = ["derive"]}
serde_json = "1.0.58"
serde_with = {version = "1.5.1", features = ["chrono"]}
string_cache = "0.8.0"

[dev-dependencies]
criterion = "0.3.3"
min-max-heap = "1.3.0"
pretty_assertions = "0.6.1"
