[package]
name = "extract_sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
failure = "0.1.8"
misc_utils = "2.5.2"
sequences = { path = "../sequences", features = [ "read_pcap" ] }
structopt = "0.3.19"
