[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "extract_sequence"
version = "0.1.0"

[dependencies]
anyhow = "1.0.34"
env_logger = "0.8.1"
misc_utils = "4.0.0"
sequences = {path = "../sequences", features = ["read_pcap"]}
structopt = "0.3.20"
