[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "extract_sequence"
version = "0.1.0"

[dependencies]
anyhow = "1.0.54"
env_logger = "0.9.0"
misc_utils = "4.0.1"
sequences = {path = "../sequences", features = ["read_pcap"]}
structopt = "0.3.26"
