[package]
name = "extract_sequence"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = [ "serde" ] }
env_logger = "0.6.0"
failure = "0.1.5"
log = "0.4.6"
pcap = "0.7.0"
pnet = { version = "0.22.0", features = [ "pcap" ] }
ron = "0.4.1"
rustls = "0.15.1"
sequences = { path = "../sequences" }
serde = { version = "1.0.89", features = [ "derive" ] }

[dev-dependencies]
pretty_assertions = "0.6.1"
