[package]
name = "plot"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
pyo3 = { version = "0.5.3", features = [ "python3" ] }

[dev-dependencies]
tempfile = "3.0.7"
