[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "taskmanager"
version = "0.1.0"

[dependencies]
anyhow = "1.0.36"
chrome = {path = "../chrome"}
chrono = "0.4.19"
diesel = {version = "1.4.5", features = ["chrono", "postgres"]}
diesel-derive-enum = {version = "1.1.0", features = ["postgres"]}
diesel_migrations = "1.4.0"
encrypted-dns = {path = ".."}
env_logger = "0.8.2"
log = "0.4.11"
misc_utils = "4.0.0"
once_cell = "1.5.2"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = {version = "0.10.31", features = ["vendored"]}
rayon = "1.5.0"
sequences = {path = "../sequences", features = ["read_pcap"]}
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.60"
structopt = "0.3.21"
tempfile = "3.1.0"
toml = "0.5.7"
url = "2.2.0"
wait-timeout = "0.2.0"
