[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrome = { path = "../chrome" }
chrono = "0.4.9"
diesel = { version = "1.4.2", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
diesel_migrations = "1.4.0"
encrypted-dns = { path = ".." }
env_logger = "0.7.0"
failure = "0.1.5"
lazy_static = "1.4.0"
log = "0.4.8"
misc_utils = "2.4.0"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = { version = "0.10.25", features = ["vendored"] }
rayon = "1.2.0"
sequences = { path = "../sequences" }
serde = { version = "1.0.101", features = [ "derive" ] }
serde_json = "1.0.41"
structopt = "0.3.3"
tempfile = "3.1.0"
toml = "0.5.3"
wait-timeout = "0.2"
