[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrome = { path = "../chrome" }
chrono = "0.4.13"
diesel = { version = "1.4.5", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "1.1.0", features = ["postgres"] }
diesel_migrations = "1.4.0"
encrypted-dns = { path = ".." }
env_logger = "0.7.1"
failure = "0.1.8"
log = "0.4.8"
misc_utils = "2.5.2"
once_cell = "1.4.0"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = { version = "0.10.29", features = ["vendored"] }
rayon = "1.3.1"
sequences = { path = "../sequences", features = [ "read_pcap" ] }
serde = { version = "1.0.114", features = [ "derive" ] }
serde_json = "1.0.56"
structopt = "0.3.14"
tempfile = "3.1.0"
toml = "0.5.6"
url = "2.1.1"
wait-timeout = "0.2.0"
