[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrome = { path = "../chrome" }
chrono = "0.4.4"
diesel = { version = "1.4.1", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
diesel_migrations = "1.4.0"
encrypted-dns = { path = ".." }
env_logger = "0.6.0"
failure = "0.1.5"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.3.0"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = "*"
rayon = "1.0.3"
sequences = { path = "../sequences" }
serde = { version = "1.0.85", features = [ "derive" ] }
serde_json = "1.0.38"
structopt = "0.2.14"
tempfile = "3.0.5"
toml = "0.4.10"
wait-timeout = "0.2"
xvfb = { path = "../xvfb" }
