[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = "0.4.4"
diesel = { version = "1.3.2", features = ["chrono", "sqlite"] }
diesel-derive-enum = { version = "0.4.3", features = ["sqlite"] }
failure = "0.1.1"
