[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrome = { path = "../chrome" }
chrono = "0.4.4"
diesel = { version = "1.3.2", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
diesel_migrations = "1.3.0"
encrypted-dns = { path = ".." }
env_logger = "0.6.0"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.0.0"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = "*"
rayon = "1.0.3"
sequences = { path = "../sequences" }
serde = { version = "1.0.70", features = [ "derive" ] }
serde_json = "1.0.33"
structopt = "0.2.13"
tempfile = "3.0.4"
toml = "0.4.8"
wait-timeout = { git = "https://github.com/alexcrichton/wait-timeout" }
xvfb = { path = "../xvfb" }
