[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = "0.4.4"
diesel = { version = "1.3.2", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
encrypted-dns = { path = ".." }
env_logger = "0.5.10"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.0.0"
rayon = "1.0.3"
sequences = { path = "../sequences" }
serde = { version = "1.0.70", features = [ "derive" ] }
structopt = "0.2.13"
toml = "0.4.8"
