[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrome = { path = "../chrome" }
chrono = "0.4.4"
diesel = { version = "1.4.2", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
diesel_migrations = "1.4.0"
encrypted-dns = { path = ".." }
env_logger = "0.6.1"
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
misc_utils = "2.3.1"
# Needed for Postgres. https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = "*"
rayon = "1.0.3"
sequences = { path = "../sequences" }
serde = { version = "1.0.91", features = [ "derive" ] }
serde_json = "1.0.39"
structopt = "0.2.15"
tempfile = "3.0.8"
toml = "0.5.1"
wait-timeout = "0.2"
