[package]
name = "taskmanager"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = "0.4.4"
diesel = { version = "1.3.2", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
encrypted-dns = { path = ".." }
env_logger = "0.5.10"
failure = "0.1.1"
lazy_static = "1.0.1"
log = "0.4.3"
misc_utils = "2.0.0"
rayon = "1.0.1"
sequences = { path = "../sequences" }
serde = "1.0.70"
serde_derive = "1.0.70"
structopt = "0.2.11"
toml = "0.4.6"
