working_directory = "/mnt/data/Downloads/taskmanager-test"
database = "postgres://taskmanager@/taskmanager"
per_domain_datasets = 2
per_domain_datasets_repeated_measurements = 2
# Set a high initial priority, such that the repeated measurements can get lower values
initial_priority = 1000000
max_allowed_dist_difference = 2.5
max_allowed_dist_difference_abs = 300
num_executors = 2
refresh_cache_seconds = 3600
docker_image = "projects.cispa.saarland:5005/bushart/encrypted-dns/dnscapture"

# [ssh]
# remote_name = "dnspi"
# docker_image = "projects.cispa.saarland:5005/bushart/encrypted-dns/dnscapture-pi"
