working_directory = "/mnt/data/Downloads/new-task-setup"
# database = "/mnt/data/Downloads/new-task-setup/tasks.db"
database = "postgres://taskmanager@/taskmanager"
per_domain_datasets = 10
max_allowed_dist_difference = 2.5
max_allowed_dist_difference_abs = 300

[[executors]]
name = "fedora28chrome"
sshconnect = "fedora28chrome"
working_directory = "/home/jbushart/dnscaptures"

[[executors]]
name = "fedora28chrome2"
sshconnect = "fedora28chrome2"
working_directory = "/home/jbushart/dnscaptures"
