# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
with_docs = true
import_types = ["diesel::sql_types::*", "models::TaskStateMapping"]
patch_file = "schema.patch"
