[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "chrome"
version = "0.1.0"

[dependencies]
chrono = "0.4.20"
serde = {version = "1.0.137", features = ["derive"]}
serde_with = {version = "1.13.0", features = ["chrono"]}
