[package]
name = "chrome"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
chrono = "0.4.6"
serde = { version = "1.0.79", features = [ "derive" ] }
serde_with = { version = "0.2.2", features = [ "chrono" ] }
