[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "chrome"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
serde = {version = "1.0.126", features = ["derive"]}
serde_with = {version = "1.8.1", features = ["chrono"]}
