[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "chrome"
version = "0.1.0"

[dependencies]
chrono = "0.4.15"
serde = {version = "1.0.116", features = ["derive"]}
serde_with = {version = "1.5.0-alpha.2", features = ["chrono"]}
