[package]
name = "dnstap"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
failure = "0.1.5"
framestream = { path = "../framestream" }
log = "0.4.6"
misc_utils = "2.2.0"
protobuf = "2.0.5"
trust-dns-proto = "0.7.0"
