[package]
name = "dnstap"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
failure = "0.1.5"
framestream = { path = "../framestream" }
log = "0.4.8"
misc_utils = "2.4.0"
protobuf = "2.8.0"
trust-dns-proto = "0.8.0"

# [build-dependencies]
# protoc-rust = "2.7.0"
