[package]
name = "plot-dnstap"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sequences = { path = "../sequences" }
env_logger = "0.7.1"
log = "0.4.8"
pyo3 = "0.8.3"
structopt = "0.3.5"
failure = "0.1.6"
serde_json = "1.0.42"
