[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.8"
env_logger = "0.6.2"
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.18", features =  ["async-await", "nightly"] }
lazy_static = "1.4.0"
log = "0.4.8"
openssl = { version = "0.10.24", features = [ "vendored" ] }
openssl-probe = "0.1.2"
rand = "0.7.0"
sequences = { path = "../sequences" }
serde_json = "1.0.40"
structopt = "0.3.0"
tokio = "0.2.0-alpha.2"
tokio-openssl = "0.4.0-alpha.2"
tokio-timer = { version = "0.3.0-alpha.2", features = [ "async-traits" ] }
trust-dns-proto = "0.7.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
