[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
env_logger = "0.6.0"
failure = "0.1.5"
futures = "0.1.25"
log = "0.4.6"
rand = "0.6.5"
rustls = "0.15.1"
structopt = "0.2.14"
tokio = { version = "0.1.16", features = [ "async-await-preview" ] }
tokio-async-await = "0.1.5"
tokio-rustls = "0.9.0"
tokio-timer = "0.2.10"
trust-dns-proto = "0.7.1"
webpki = "0.19.1"
webpki-roots = "0.16.0"
