[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.10"
env_logger = "0.7.1"
failure = "0.1.6"
futures = { version = "0.3.1", default-features = false, features = [ "std" ] }
log = "0.4.8"
once_cell = "1.3.1"
openssl = { version = "0.10.26", features = [ "vendored" ] }
openssl-probe = "0.1.2"
rand = "0.7.3"
sequences = { path = "../sequences" }
serde_json = "1.0.45"
structopt = "0.3.8"
tokio = { version = "0.2.10", features = [ "fs", "io-util", "stream", "tcp", "time" ] }
tokio-openssl = "0.4.0"
trust-dns-proto = { git = "https://github.com/jonasbb/trust-dns", branch = "fix-empty-option-at-end-of-edns", default-features = false }

[dev-dependencies]
pretty_assertions = "0.6.1"
