[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.9"
env_logger = "0.7.1"
failure = "0.1.6"
futures-preview = { version = "=0.3.0-alpha.19", features =  [ "async-await" ] }
lazy_static = "1.4.0"
log = "0.4.8"
openssl = { version = "0.10.25", features = [ "vendored" ] }
openssl-probe = "0.1.2"
rand = "0.7.2"
sequences = { path = "../sequences" }
serde_json = "1.0.41"
structopt = "0.3.4"
tokio = "0.2.0-alpha.6"
tokio-openssl = "0.4.0-alpha.6"
tokio-timer = { version = "0.3.0-alpha.6", features = [ "async-traits" ] }
trust-dns-proto = { version = "=0.8.0", default-features = false }

[dev-dependencies]
pretty_assertions = "0.6.1"
