[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
env_logger = "0.6.0"
futures = "0.1.25"
log = "0.4.6"
native-tls = "0.2.2"
tokio = { version = "0.1.15", features = [ "async-await-preview" ] }
tokio-async-await = "0.1.5"
tokio-tls = "0.2.1"
tokio-rustls = "0.9.0"
webpki = "0.19.1"
rustls = "0.15.1"
webpki-roots = "0.16.0"
