[package]
name = "tlsproxy"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.7"
env_logger = "0.6.1"
failure = "0.1.5"
futures = "0.1.28"
lazy_static = "1.3.0"
log = "0.4.6"
openssl = { version = "0.10.23", features = [ "vendored" ] }
openssl-probe = "0.1.2"
rand = "0.6.5"
sequences = { path = "../sequences" }
serde_json = "1.0.39"
structopt = "0.2.18"
tokio = { version = "=0.1.18", features = [ "async-await-preview" ] }
tokio-async-await = "=0.1.6"
tokio-openssl = "0.3.0"
tokio-timer = "0.2.11"
trust-dns-proto = "0.7.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
