[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "tlsproxy"
version = "0.1.0"

[dependencies]
anyhow = "1.0.34"
byteorder = "1.3.4"
chrono = "0.4.19"
env_logger = "0.8.1"
futures = {version = "0.3.8", default-features = false, features = ["std"]}
log = "0.4.11"
once_cell = "1.5.2"
openssl = {version = "0.10.30", features = ["vendored"]}
openssl-probe = "0.1.2"
rand = "0.7.3"
sequences = {path = "../sequences"}
serde_json = "1.0.59"
structopt = "0.3.20"
thiserror = "1.0.22"
tokio = {version = "0.2.22", features = ["fs", "io-util", "stream", "tcp", "time"]}
tokio-openssl = "0.4.0"
trust-dns-proto = {version = "0.20.0-alpha.3", default-features = false}
