[package]
name = "framestream"
version = "0.1.2"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Frame Streams implementation in Rust"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-framestream"
repository = "https://github.com/jedisct1/rust-framestream"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.11"
failure = "0.1.5"
failure_derive = "0.1.1"
log = "0.4.6"
