[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "third-party-resources"
version = "0.1.0"

[dependencies]
anyhow = "1.0.34"
csv = "1.1.4"
dnstap = {path = "../dnstap"}
env_logger = "0.8.2"
log = "0.4.11"
misc_utils = "4.0.0"
once_cell = "1.5.2"
rayon = "1.5.0"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
structopt = "0.3.21"
