[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "third-party-resources"
version = "0.1.0"

[dependencies]
anyhow = "1.0.38"
csv = "1.1.5"
dnstap = {path = "../dnstap"}
env_logger = "0.8.3"
log = "0.4.14"
misc_utils = "4.0.1"
once_cell = "1.7.0"
rayon = "1.5.0"
serde = {version = "1.0.123", features = ["derive"]}
serde_json = "1.0.62"
structopt = "0.3.21"
