[package]
name = "third-party-resources"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.1.0"
dnstap = { path = "../dnstap" }
env_logger = "0.6.2"
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
misc_utils = "2.4.0"
rayon = "1.1.0"
serde = { version = "1.0.94", features = [ "derive" ] }
serde_json = "1.0.39"
structopt = "0.2.18"
