[package]
name = "third-party-resources"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
dnstap = { path = "../dnstap" }
env_logger = "0.7.1"
failure = "0.1.6"
lazy_static = "1.4.0"
log = "0.4.8"
misc_utils = "2.5.1"
rayon = "1.2.0"
serde = { version = "1.0.102", features = [ "derive" ] }
serde_json = "1.0.41"
structopt = "0.3.4"
