[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "third-party-resources"
version = "0.1.0"

[dependencies]
anyhow = "1.0.40"
csv = "1.1.6"
dnstap = {path = "../dnstap"}
env_logger = "0.8.3"
log = "0.4.14"
misc_utils = "4.0.1"
once_cell = "1.7.2"
rayon = "1.5.1"
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
structopt = "0.3.21"
