[package]
name = "third-party-resources"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
dnstap = { path = "../dnstap" }
env_logger = "0.7.1"
failure = "0.1.8"
log = "0.4.8"
misc_utils = "2.5.2"
once_cell = "1.4.0"
rayon = "1.3.1"
serde = { version = "1.0.112", features = [ "derive" ] }
serde_json = "1.0.55"
structopt = "0.3.14"
