[package]
name = "third-party-resources"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[dependencies]
csv = "1.0.2"
dnstap = { path = "../dnstap" }
env_logger = "0.5.13"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.1.0"
rayon = "1.0.3"
serde = { version = "1.0.80", features = [ "derive" ] }
serde_json = "1.0.32"
structopt = "0.2.13"
structopt-derive = "0.2.12"
