[package]
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"
name = "third-party-resources"
version = "0.1.0"

[dependencies]
anyhow = "1.0.33"
csv = "1.1.3"
dnstap = {path = "../dnstap"}
env_logger = "0.7.1"
log = "0.4.11"
misc_utils = "3.0.0"
once_cell = "1.4.1"
rayon = "1.4.1"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
structopt = "0.3.19"
