[package]
name = "third-party-resources"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
dnstap = { path = "../dnstap" }
env_logger = "0.6.0"
failure = "0.1.3"
lazy_static = "1.2.0"
log = "0.4.6"
misc_utils = "2.1.0"
rayon = "1.0.3"
serde = { version = "1.0.84", features = [ "derive" ] }
serde_json = "1.0.35"
structopt = "0.2.14"
structopt-derive = "0.2.12"
