[package]
name = "pylib"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[lib]
name = "pylib"
crate-type = [ "lib", "cdylib" ]

[dependencies]
failure = "0.1.1"
misc_utils = "1.4.0"
serde = "1.0.66"
serde_derive = "1.0.66"
serde-pickle = "0.4.1"

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3/"
features = [ "extension-module", "python3" ]

