[package]
name = "pylib"
version = "0.1.1"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[lib]
name = "pylib"
crate-type = [ "cdylib" ]

[dependencies]
encrypted-dns = { path = ".." }
failure = "0.1.3"
sequences = { path = "../sequences" }

[dependencies.pyo3]
version = "0.5.0-alpha.2"
features = [ "python3" ]
