[package]
name = "pylib"
version = "0.1.1"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[lib]
name = "pylib"
crate-type = [ "cdylib" ]

[dependencies]
encrypted-dns = { path = ".." }
failure = "0.1.1"

[dependencies.pyo3]
version = "0.4.0"
features = [ "python3" ]
