[package]
name = "pylib"
version = "0.1.1"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[lib]
name = "pylib"
crate-type = [ "cdylib" ]

[dependencies]
encrypted-dns = { path = ".." }
failure = "0.1.5"
sequences = { path = "../sequences" }

[dependencies.pyo3]
version = "0.5.4"
features = [ "python3" ]
