[package]
name = "pylib"
version = "0.2.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[lib]
name = "pylib"
crate-type = [ "cdylib" ]

[dependencies]
encrypted-dns = { path = ".." }
failure = "0.1.6"
sequences = { path = "../sequences", features = [ "read_pcap" ] }

[dependencies.pyo3]
version = "0.8.1"
features = [ "python3" ]
