[package]
name = "pylib"
version = "0.3.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[lib]
name = "pylib"
crate-type = [ "cdylib" ]

[dependencies]
encrypted-dns = { path = ".." }
failure = "0.1.6"
misc_utils = "2.5.1"
pyo3 = "0.8.5"
sequences = { path = "../sequences", features = [ "read_pcap" ] }
serde_json = "1.0.47"
